### ISSUE TITLE
Which  hyper-parameter  should i set to get the same mAP of paper in NUS-WIDE and CIFAR-10

### ISSUE THREAD

**Issue by swuxyj** [liyunqianggyn/Push-for-Quantization-Deep-Fisher-Hashing#1]
it is a nice work！but i can't get the same mAP in NUS-WIDE  and CIFAR-10.  
the hyper-paramter i  set  is {'margin': 3, 'mu': 0.1, 'vul': 1, 'nta': 1, 'eta': 0.5}.  
Can you tell me which hyperparameter I should modify？

**Comment by liyunqianggyn** [comment]
Hello, could you increase the "mu" to 1 and decrease the "margin" to 1.
